{% set name = "pymrio" %}
{% set version = "0.5.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymrio-{{ version }}.tar.gz
  sha256: 57d316e17b55740c787b192134bc83f003220a15e0c3225c7253ad34cd0d3b74

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - pyarrow >=11.0
    - pandas >=1.5
    - numpy >=1.20
    - matplotlib-base >=2.0.0
    - requests >=2.18
    - xlrd >1.1.0
    - openpyxl >=3.0.6,< 3.1.1
    - docutils >=0.14
    - faker >=18.4.0

test:
  imports:
    - pymrio
    - pymrio.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/konstantinstadler/pymrio
  summary: A python module for automating input output calculations and generating reports
  license: LGPL-3.0-or-later
  # License file manually packaged. See: https://github.com/konstantinstadler/pymrio/pull/56
  license_file: LICENSE
  description: |
    Pymrio is an open source tool for analysing global environmentally extended 
    multi-regional input-output tables (EE MRIOs). Pymrio aims to provide a 
    high-level abstraction layer for global EE MRIO databases in order to 
    simplify common EE MRIO data tasks. Pymrio includes automatic download 
    functions and parsers for available EE MRIO databases like EXIOBASE, WIOD 
    and EORA26. It automatically checks parsed EE MRIOs for missing data 
    necessary for calculating standard EE MRIO accounts (such as footprint, 
    territorial, impacts embodied in trade) and calculates all missing tables. 
    Various data report and visualization methods help to explore the dataset 
    by comparing the different accounts across countries.
  doc_url: https://pymrio.readthedocs.io/en/latest/
  dev_url: https://github.com/konstantinstadler/pymrio/blob/master/CONTRIBUTING.rst

extra:
  recipe-maintainers:
    - konstantinstadler
